# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ceres_arm_controller

  ceres_arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_structure_joint
      - base_pivot_shoulder_gearbox_joint
      - bicep_tube_gearbox_joint
      - forearm_tube_wrist_gearbox_joint
      - gripper_claw_joint
    action_ns: follow_joint_trajectory
    default: true