
    planning_frame: base_structure_link
    publish_period: 0.01  # 100 Hz
    max_expected_latency: 0.1 #delay between sending a command and the robot executing it. 

    command_in_type: "speed_units" #speed_untis cmds are in m/s and rad/s
    scale:
      linear: 0.2 #Max linear speed in m/s
      rotational: 0.8 #Max rotational speed in rad/s
      joint: 0.5 


        # Output and feedback (I have not clue this means/does... figure out later)
    command_out_type: trajectory_msgs/JointTrajectory #T ype of command to be published by servo
    command_out_topic: joint_trajectory # the topic on which the servo will publish the joint trajectory 
                                        # Change this to the topic the controller requires

    publish_joint_velocities: true # Whether to publish joint velocities

    # Robot groups
    move_group_name: ceres_arm_config
    
    # Command input topics
    cartesian_command_in_topic: /goal_twist # The topic on which the servo receives twist commands.
    joint_command_in_topic: /joint_command
    pose_command_in_topic: /pose_goal

    # Collision checking
    check_collisions: true
    collision_check_rate: 10.0  # Hz
    self_collision_proximity_threshold: 0.01
    scene_collision_proximity_threshold: 0.02
